### ISSUE TITLE
`toArray` method?

### ISSUE THREAD

**Issue by clayrat** [purescript/purescript-maps#67]
Is it acceptable/possible to have a direct `forall k v. Map k v -> Array (Tuple k v)` method, as to not go through an intermediary `List`?

**Comment by garyb** [comment]
I'm not sure what the implementation for that would look like, since building it with a `List` and then converting to an `Array` is probably more efficient than doing the same thing directly with an `Array` (since it'd be O(n) for each addition to the `Array` but is O(1) for the `List`). 

Maybe there's a way using an `STArray` or something, but I guess you'd still end up with something very similar as doing the `List` -> `Array` conversion, as you'd still have to fold over an implicit list of tuples, if not an actual `List`.

**Comment by hdgarrood** [comment]
Fixed by the addition of `toUnfoldable` in https://github.com/purescript/purescript-maps/commit/103122a51d0280c07849894d9ea04f30a12e9f38.
